### ISSUE TITLE
Version 4.2.19.25 not working in flatpak

### ISSUE THREAD

**Issue by Carstijn** [bdbcat/oesenc_pi#111]
Hi @bdbcat ,

I upgraded the oesenc plugin on my linux/fedora 33/flatpak install to the latest version (4.2.19.25). I am not entirely sure what version I had before the update.

In the log below I reinstall the plugin, after reinstalling the gui shows it and has the enabled checkmark but nothing happens. After the installation there is no mention of the plugin in the log.

Can I download the previous versions somewhere so I can test at which version it stoped working?

>  20:43:30.090 MESSAGE update_mgr.cpp:246 Selected update: oeSENC
> 20:43:30.099 MESSAGE pluginmanager.cpp:1703 PlugInManager: Deactivating PlugIn: 
> 20:43:30.100 MESSAGE pluginmanager.cpp:437 Uninstalling oeSENC
> 20:43:30.100 MESSAGE pluginmanager.cpp:1703 PlugInManager: Deactivating PlugIn: 
> 20:43:30.108 MESSAGE pluginmanager.cpp:444 Installing oeSENC
> 20:43:30.108 MESSAGE PluginHandler.cpp:1080 Installing oeSENC-4.2.19.25_flatpak-18.08-x86_64.tar.gz from local cache
> 20:43:31.230 MESSAGE pluginmanager.cpp:1098 PlugInManager: loading plugins from /home/sander/.var/app/org.opencpn.OpenCPN/lib;/app/extensions/lib/opencpn;/app/lib/opencpn
> 20:43:31.230 MESSAGE pluginmanager.cpp:1051 Using LD_LIBRARY_PATH: /home/sander/.var/app/org.opencpn.OpenCPN/lib:/app/extensions/lib/opencpn:/app/lib/opencpn:/home/sander/.var/app/org.opencpn.OpenCPN/lib:/app/extensions/lib/opencpn:/app/lib/opencpn:/home/sander/.var/app/org.opencpn.OpenCPN/lib:/app/extensions/lib/opencpn:/app/lib/opencpn:/home/sander/.var/app/org.opencpn.OpenCPN/lib:/app/extensions/lib/opencpn:/app/lib/opencpn:/home/sander/.var/app/org.opencpn.OpenCPN/lib:/app/extensions/lib/opencpn:/app/lib/opencpn:/home/sander/.var/app/org.opencpn.OpenCPN/lib:/app/extensions/lib/opencpn:/app/lib/opencpn
> 20:43:31.230 MESSAGE pluginmanager.cpp:1087 Using PATH: /home/sander/.var/app/org.opencpn.OpenCPN/bin:/app/extensions/bin:/app/bin:/home/sander/.var/app/org.opencpn.OpenCPN/bin:/app/extensions/bin:/app/bin:/home/sander/.var/app/org.opencpn.OpenCPN/bin:/app/extensions/bin:/app/bin:/home/sander/.var/app/org.opencpn.OpenCPN/bin:/app/extensions/bin:/app/bin:/home/sander/.var/app/org.opencpn.OpenCPN/bin:/app/extensions/bin:/app/bin:/home/sander/.var/app/org.opencpn.OpenCPN/bin:/app/extensions/bin:/app/bin:/app/bin:/usr/bin
> 20:43:31.230 MESSAGE pluginmanager.cpp:1104 Loading plugins from dir: /home/sander/.var/app/org.opencpn.OpenCPN/lib
> 20:43:31.230 MESSAGE pluginmanager.cpp:1130 PlugInManager searching for PlugIns in location /home/sander/.var/app/org.opencpn.OpenCPN/lib
> 20:43:31.231 MESSAGE pluginmanager.cpp:1167 Found 12 candidates
> 20:43:31.231 MESSAGE pluginmanager.cpp:1174 Checking plugin candidate: /home/sander/.var/app/org.opencpn.OpenCPN/lib/opencpn/libtactics_pi.so
> 20:43:31.231 MESSAGE pluginmanager.cpp:1174 Checking plugin candidate: /home/sander/.var/app/org.opencpn.OpenCPN/lib/opencpn/libclimatology_pi.so
> 20:43:31.232 MESSAGE pluginmanager.cpp:1174 Checking plugin candidate: /home/sander/.var/app/org.opencpn.OpenCPN/lib/opencpn/libweatherfax_pi.so
> 20:43:31.232 MESSAGE pluginmanager.cpp:1174 Checking plugin candidate: /home/sander/.var/app/org.opencpn.OpenCPN/lib/opencpn/libocpn_draw_pi.so
> 20:43:31.232 MESSAGE pluginmanager.cpp:1174 Checking plugin candidate: /home/sander/.var/app/org.opencpn.OpenCPN/lib/opencpn/libdashboardtactics_pi.so
> 20:43:31.232 MESSAGE pluginmanager.cpp:1174 Checking plugin candidate: /home/sander/.var/app/org.opencpn.OpenCPN/lib/opencpn/libweather_routing_pi.so
> 20:43:31.232 MESSAGE pluginmanager.cpp:1174 Checking plugin candidate: /home/sander/.var/app/org.opencpn.OpenCPN/lib/opencpn/libPolar_pi.so
> 20:43:31.232 MESSAGE pluginmanager.cpp:1174 Checking plugin candidate: /home/sander/.var/app/org.opencpn.OpenCPN/lib/opencpn/libtwocan_plugin_pi.so
> 20:43:31.232 MESSAGE pluginmanager.cpp:1174 Checking plugin candidate: /home/sander/.var/app/org.opencpn.OpenCPN/lib/opencpn/libwindvane_pi.so
> 20:43:31.232 MESSAGE pluginmanager.cpp:1174 Checking plugin candidate: /home/sander/.var/app/org.opencpn.OpenCPN/lib/opencpn/libsquiddio_pi.so
> 20:43:31.232 MESSAGE pluginmanager.cpp:1174 Checking plugin candidate: /home/sander/.var/app/org.opencpn.OpenCPN/lib/opencpn/libwatchdog_pi.so
> 20:43:31.232 MESSAGE pluginmanager.cpp:1174 Checking plugin candidate: /home/sander/.var/app/org.opencpn.OpenCPN/lib/opencpn/libotcurrent_pi.so
> 20:43:31.233 MESSAGE OCPNPlatform.cpp:1016 ChangeLocale: Language load for:  en_US
> 20:43:31.233 MESSAGE OCPNPlatform.cpp:1026 Using flatpak locales at /home/sander/.var/app/org.opencpn.OpenCPN/data/locale
> 20:43:31.234 MESSAGE OCPNPlatform.cpp:1068 ChangeLocale: Locale Init OK for:  en_US
> 20:43:31.234 MESSAGE OCPNPlatform.cpp:1081 Loading catalog for:  opencpn-squiddio_pi
> 20:43:31.235 MESSAGE OCPNPlatform.cpp:1081 Loading catalog for:  opencpn-squiddio_pi
> 20:43:31.236 MESSAGE OCPNPlatform.cpp:1081 Loading catalog for:  opencpn-wmm_pi
> 20:43:31.236 MESSAGE OCPNPlatform.cpp:1081 Loading catalog for:  opencpn-chartdldr_pi
> 20:43:31.237 MESSAGE OCPNPlatform.cpp:1081 Loading catalog for:  opencpn-grib_pi
> 20:43:31.238 MESSAGE OCPNPlatform.cpp:1087 Loading catalog for opencpn core.
> 20:43:31.238 MESSAGE OCPNPlatform.cpp:931 Getting DefaultSystemLocale...
> 20:43:31.238 MESSAGE pluginmanager.cpp:1104 Loading plugins from dir: /app/extensions/lib/opencpn
> 20:43:31.238 MESSAGE pluginmanager.cpp:1130 PlugInManager searching for PlugIns in location /app/extensions/lib/opencpn
> 20:43:31.238 MESSAGE pluginmanager.cpp:1145    Directory /app/extensions/lib/opencpn does not exist.
> 20:43:31.238 MESSAGE pluginmanager.cpp:1104 Loading plugins from dir: /app/lib/opencpn
> 20:43:31.239 MESSAGE pluginmanager.cpp:1130 PlugInManager searching for PlugIns in location /app/lib/opencpn
> 20:43:31.239 MESSAGE pluginmanager.cpp:1167 Found 4 candidates
> 20:43:31.239 MESSAGE pluginmanager.cpp:1174 Checking plugin candidate: /app/lib/opencpn/libwmm_pi.so
> 20:43:31.239 MESSAGE pluginmanager.cpp:1174 Checking plugin candidate: /app/lib/opencpn/libdashboard_pi.so
> 20:43:31.239 MESSAGE pluginmanager.cpp:1174 Checking plugin candidate: /app/lib/opencpn/libchartdldr_pi.so
> 20:43:31.239 MESSAGE pluginmanager.cpp:1174 Checking plugin candidate: /app/lib/opencpn/libgrib_pi.so
> 20:43:31.240 MESSAGE OCPNPlatform.cpp:1016 ChangeLocale: Language load for:  en_US
> 20:43:31.240 MESSAGE OCPNPlatform.cpp:1026 Using flatpak locales at /home/sander/.var/app/org.opencpn.OpenCPN/data/locale
> 20:43:31.241 MESSAGE OCPNPlatform.cpp:1068 ChangeLocale: Locale Init OK for:  en_US
> 20:43:31.241 MESSAGE OCPNPlatform.cpp:1081 Loading catalog for:  opencpn-squiddio_pi
> 20:43:31.242 MESSAGE OCPNPlatform.cpp:1081 Loading catalog for:  opencpn-squiddio_pi
> 20:43:31.242 MESSAGE OCPNPlatform.cpp:1081 Loading catalog for:  opencpn-wmm_pi
> 20:43:31.243 MESSAGE OCPNPlatform.cpp:1081 Loading catalog for:  opencpn-chartdldr_pi
> 20:43:31.244 MESSAGE OCPNPlatform.cpp:1081 Loading catalog for:  opencpn-grib_pi
> 20:43:31.244 MESSAGE OCPNPlatform.cpp:1087 Loading catalog for opencpn core.
> 20:43:31.245 MESSAGE OCPNPlatform.cpp:931 Getting DefaultSystemLocale...

**Comment by bdbcat** [comment]
There is a problem with the oesenc flatpak CI build.
Investigating now....

**Comment by bdbcat** [comment]
Corrected now in Version 4.2.19.26, available in master catalog as an update.

**Comment by Carstijn** [comment]
@bdbcat Works!
