### ISSUE TITLE
Opencpn 5.0.522: The managed plugin installs an ARMHF binary on ARM64

### ISSUE THREAD

**Issue by hreuver0183** [bdbcat/oesenc_pi#57]
When I tested the managed plugin I found out it installs a not working binary for oeserverd.
Probably the ARMHF binary is installed on an ARM64 system.

Some textual issues:
The version number 4.0.2 is not visible in the plugin dialog, it shows 4.0 or 4.0.0.
The change from 4.0.2 to "managed" 4.0.0 is called an "upgrade"

**Comment by bdbcat** [comment]
What is the operating system you are installing for?

**Comment by hreuver0183** [comment]
Ubuntu 18.04 / ARM64

**Comment by bdbcat** [comment]
Ahhh...
There should be no managed plugins offered for 18.04/ARM64. This is a bug in the metadata processing.  I will address.
We are not (yet) building managed plugins for ARM64 at all.  Low priority.  Only building for raspbian ARMHF, "stretch" and "buster".
Meanwhile, the current Legacy plugin for ARM64 bionic(1.0.6) should be available from Ubuntu PPA.   Same code, except for installer support...
Dave
