### ISSUE TITLE
Confusion about branches master and ci

### ISSUE THREAD

**Issue by rgleason** [bdbcat/oesenc_pi#83]
Dave,
I woke up this morning and realized something.
I had thought you were keeping "ci" for the Plugin Manager code and "master" for the legacy code.
From what I can determine it now looks like "master" is now for the Plugin Manager code.
Is that correct?
I am trying to stay current.

**Comment by bdbcat** [comment]
Correct.
Branch "ci" is dormant.  "master" is used to build managed plugins now.

**Comment by rgleason** [comment]
Thanks
