### ISSUE TITLE
Flatpak: USB dongle not detected

### ISSUE THREAD

**Issue by Carstijn** [bdbcat/oesenc_pi#86]
Hi,

I am running OpenCPN from Flatpak on my Fedora 31 machine, plugin version 4.2.6 installed from the plugin manager. When I try to generate a USB key system ID File, I get a error message:

![image](https://user-images.githubusercontent.com/23108348/79637427-d73ab500-817f-11ea-8d05-31453d6c4aba.png)
The dongle is visible via lsusb:
**Bus 001 Device 002: ID 1547:1000 SG Intec Ltd & Co KG SG-Lock[U2]**

In the OpenCPN.log file I see this error:
**oesenc_pi.cpp:3961 sh: ip: command not found**

Anything I can try to get this working?

**Comment by bdbcat** [comment]
Please check to logfile, looking for something like this:

```
MESSAGE oesenc_pi.cpp:739 Path to oeserverd is: /home/dsr/.var/app/org.opencpn.OpenCPN/bin/oeserverd
19:59:53.196 MESSAGE oesenc_pi.cpp:3846 IsDongleAvailable()::oeserverd execution results:
19:59:53.196 MESSAGE oesenc_pi.cpp:3849 1
19:59:53.196 MESSAGE oesenc_pi.cpp:742 Dongle detected

```

From a CLI, try:

` /home/{YOUR USER NAME}/.var/app/org.opencpn.OpenCPN/bin/oeserverd -a
`
Dave

**Comment by Carstijn** [comment]
Hi Dave!

It doesn't print to much:
 **.var/app/org.opencpn.OpenCPN/bin/oeserverd -a
oeserverd Version 1.14**

**Comment by bdbcat** [comment]
That is the correct response.

Did you find the log entries shown above?

**Comment by Carstijn** [comment]
Sorry missed that part, found it, not to helpful:

**16:39:24.313 MESSAGE pluginmanager.cpp:1094 Checking plugin candidate: /home/sander/.var/app/org.opencpn.OpenCPN/lib/opencpn/liboesenc_pi.so
16:39:24.313 MESSAGE pluginmanager.cpp:2122 PlugInManager: Loading PlugIn: /home/sander/.var/app/org.opencpn.OpenCPN/lib/opencpn/liboesenc_pi.so
16:39:24.319    INFO pluginmanager.cpp:2293 PlugInManager:  /home/sander/.var/app/org.opencpn.OpenCPN/lib/opencpn/liboesenc_pi.so
16:39:24.320 MESSAGE oesenc_pi.cpp:739 Path to oeserverd is: /home/sander/.var/app/org.opencpn.OpenCPN/bin/oeserverd
16:39:27.456 MESSAGE oesenc_pi.cpp:3846 IsDongleAvailable()::oeserverd execution results:
16:39:27.456 MESSAGE oesenc_pi.cpp:3849 0
16:39:27.456 MESSAGE oesenc_pi.cpp:744 No Dongle detected
16:39:27.629 MESSAGE oesenc_pi.cpp:955 oesenc_pi:  Calculated pix/mm = 3.77754
16:39:27.638 MESSAGE oesenc_pi.cpp:3066 oeSENC_PI:  OpenGL-> Minimum cartographic line width:  1.0
16:39:27.687 MESSAGE OCPNPlatform.cpp:1046 Loading catalog for:  opencpn-oesenc_pi
16:39:27.710 MESSAGE oesenc_pi.cpp:955 oesenc_pi:  Calculated pix/mm = 3.77754
16:39:27.781 MESSAGE OCPNPlatform.cpp:1046 Loading catalog for:  opencpn-oesenc_pi
**

**Comment by bdbcat** [comment]
So, indeed, you dongle is not found.
"16:39:27.456 MESSAGE oesenc_pi.cpp:744 No Dongle detected"

Try these cli commands:

```
/home/{YOUR USER NAME}/.var/app/org.opencpn.OpenCPN/bin/oeserverd -t

/home/{YOUR USER NAME}/.var/app/org.opencpn.OpenCPN/bin/oeserverd -s

```
These commands will test for the dongle directly.

**Comment by Carstijn** [comment]
Humm... I updated to the latest flatpack version, and updated the plug-in to the latest version. Now I am not able to load the plug-in, and files are in the wrong location on disk disk:
.var/app/org.opencpn.OpenCPN/unknown-prefix/bin/oeserverd

**.var/app/org.opencpn.OpenCPN/unknown-prefix/bin/oeserverd -t
0**

**.var/app/org.opencpn.OpenCPN/unknown-prefix/bin/oeserverd -s
0**

**Comment by bdbcat** [comment]
This is WIP.  Such is Alpha testing....
Please stand by.
Dave

**Comment by bdbcat** [comment]
Please try:
`ls -la .var/app/org.opencpn.OpenCPN/unknown-prefix/lib
`

**Comment by Carstijn** [comment]
ls -la .var/app/org.opencpn.OpenCPN/unknown-prefix/lib 
total 88
drwxr-xr-x. 3 sander sander  4096 Apr 19 17:04 .
drwxr-xr-x. 5 sander sander  4096 Apr 19 17:04 ..
-rwxr-xr-x. 1 sander sander 37586 Jan  1  1970 libsgllnx64-2.29.02.so
-rwxr-xr-x. 1 sander sander 34824 Jan  1  1970 libusb-0.1.so.4
drwxr-xr-x. 2 sander sander  4096 Apr 19 17:04 opencpn

Just noticing, I have no problem with some additional effort to get to a working state ;-)

**Comment by bdbcat** [comment]
Carstijn...
The OpenCPN flatpak build is broken just now.  We will need a day to rebuild and re-sync the flatpak repos.  Please stand by.

**Comment by Carstijn** [comment]
So the flatpak build and plugin seem to be working order again:
**var/app/org.opencpn.OpenCPN/bin/oeserverd -t
0**

**.var/app/org.opencpn.OpenCPN/bin/oeserverd -s
0**

ls -la .var/app/org.opencpn.OpenCPN/lib/
total 88
drwxr-xr-x. 3 sander sander  4096 Jan  1  1970 .
drwxr-xr-x. 9 sander sander  4096 Apr 21 08:34 ..
-rwxr-xr-x. 1 sander sander 37586 Jan  1  1970 libsgllnx64-2.29.02.so
-rwxr-xr-x. 1 sander sander 34824 Jan  1  1970 libusb-0.1.so.4
drwxr-xr-x. 2 sander sander  4096 Jan  1  1970 opencpn

**Comment by hreuver0183** [comment]
The OpenCPN manual was updated today. There is a new version of OpenCPN (still beta), and a step-by-step method to check the USB dongle is (for now) included in the flatpak installation.

Could you try if the SG lock / USB dongle troubleshooting works for you?
(Most of it follows the commands mentioned above).

I think for your answer you can skip straight to the part of the 98-sglock.rules.
[https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:getting_started:opencpn_installation:flatpak](url)
Feedback will be appreciated.

**Comment by Carstijn** [comment]
Hi!

The udev rule did the trick.

I guess a "sudo udevadm trigger" should be added to the manual to reload the udev rules.

**Comment by hreuver0183** [comment]
Since USB is supposed to be hot-pluggable it is easier to tell people to remove and reinsert the dongle.

Most people who take the hint a command is sufficient don't need the manual to change the permissions in the first place ;-)

But with this I think this issue can be closed.
