### ISSUE TITLE
Debian folders and files.

### ISSUE THREAD

**Issue by rgleason** [bdbcat/oesenc_pi#88]
In this folder I have several files with "oesenc_pi,  oesenc-pi, oesenc. oesenc-pi.debhelper.log"
C:\Users\Rick\Documents\GitHub\squiddio_pi\debian

Is it required that some of these filenames be changed for debian to work?  
IE: Is it ok to just leave this as is?

**Comment by bdbcat** [comment]
Rick...
I think it is safe to delete these files.  Just some leftover build artifacts.

**Comment by rgleason** [comment]
Thanks, will remove from squiddio, oesenc, vdr
