### ISSUE TITLE
Android builds of PI

### ISSUE THREAD

**Issue by rgleason** [bdbcat/oesenc_pi#99]
Dave is it time to add the android builds to plugins?   IE How mature is this at this point?
Sean wrote and is interested in getting this going on all his plugins.

**Comment by rgleason** [comment]
I have tried it in Watchdog, but both android seem to fail.

https://github.com/rgleason/watchdog_pi/runs/1064498962

https://app.circleci.com/pipelines/github/rgleason/watchdog_pi/95/workflows/1d0c6423-7033-464a-8e31-a74c0f71fafd/jobs/1092

**Comment by bdbcat** [comment]
Rick...
I am ready to start the integration of Android build on Frontend-2.
Which plugin, based on Frontend-2, is the simplest?  That is, does not have much UI interaction, does not download private data, etc.  Could it be VDR?

btw, your build on watchdog failed for simple reason.  Read the log.  The script permission needs to be +X.

**Comment by rgleason** [comment]
Thanks Dave, I'll check the watchdog error.

I think the best plugin to use is my fork of Jon's [testplugin_pi.](https://github.com/rgleason/testplugin_pi) I will make sure you have collaboration access (sent you an invite).  Jon can them move the Android build into his repository. 

[github.com/rgleason/vdr_p](https://github.com/rgleason/vdr_pi/tree/master)i master branch (you are a collaborator)  is using your frontend1 and I will update that to make it current with your oesenc frontend and then make a PR to plugins..

Thanks

**Comment by rgleason** [comment]
BTW, watchdog and weather_routing flatpak isn't building very well, don't know why.

**Comment by rgleason** [comment]
"The script permission needs to be +X."   This 126 Error trips me up every time!  will do chmod.

**Comment by rgleason** [comment]
Error:
/bin/bash: ci/circleci-build-fedora.sh: Permission denied
Exited with code exit status 126

CHMOD For Windows:
You must be in the actual directory for the commands to work!    Also git status must show file changed.
 git update-index --add --chmod=+x <build.sh>
 git commit -m 'Make <build.sh> executable'

**Comment by bdbcat** [comment]
Rick...
Any progress on VDR Frontend-1 for Android?

**Comment by bdbcat** [comment]
Rick/Jon...
Frontend-2 for testplugin_pi has been adapted for Android builds.
The new code is in Rick's repo, in branch "android_ci".
There is still some problem with the cloudsmith-upload.sh script, which I did **not** modify.  Perhaps this is due to building from a branch other than "master", and so will self correct when the android_ci branch is merged....maybe.

Also note, on this plugin, some source files needed touch-up for Android build.  Nothing serious, and I expect we will see more of this sort of thing as we adapt more plugins to Android.
Please let me know when this patch has been merged, and a correct tarball build is available in cloudsmith for import testing on actual Android hardware.

**Comment by rgleason** [comment]
"Any progress on VDR Frontend-1 for Android?"
Sorry,  I will do that next, after a day  sail.

**Comment by rgleason** [comment]
RE: testplugin_pi   branch: android-ci     
That is great that you can make a new branch, I did not know that.
This new branch appears to have all the permissions needed to build, in travis, appveyor and circleci.
Just the flatpak and  android-armhf builds are failing.

[android-armhf failures ](https://app.circleci.com/pipelines/github/rgleason/testplugin_pi/193/workflows/8b18ede4-8fdf-4cce-b66c-5b5e2d77b30c/jobs/1774)are:

```
+ cp xml.tmp /home/circleci/project/build/testplugin_pi-1.0.132.1-android-armhf-16.xml
cp: cannot create regular file '/home/circleci/project/build/testplugin_pi-1.0.132.1-android-armhf-16.xml': Permission denied
+ cat /home/circleci/project/build/testplugin_pi-1.0.132.1-android-armhf-16.xml
```
and
```
++ pwd
+ cur_dir=/home/circleci/project
+ gunzip -f /home/circleci/project/build/testplugin_pi-1.0.132.1-android-armhf-16.tar.gz
gzip: /home/circleci/project/build/testplugin_pi-1.0.132.1-android-armhf-16.tar: Permission denie
```

The [flatpak failure](https://app.circleci.com/pipelines/github/rgleason/testplugin_pi/193/workflows/8b18ede4-8fdf-4cce-b66c-5b5e2d77b30c/jobs/1772) looks like one I've been getting in watchdog recently too.

**Comment by rgleason** [comment]
In [Cloudsmith Opencpen   testplugin-alpha  there are recent builds of v1.0.132 from your branch android-ci](https://cloudsmith.io/~opencpn/repos/testplugin-alpha/packages/?q=1.0.132.1*tarball)   one of them is a tarball for android-arm64. 

Do you want me to make a PR to plugins to add just that tarball?

**Comment by bdbcat** [comment]
The tarball in cloudsmith now is not correct.
Still working on the permission question.
I'll let you know....

**Comment by rgleason** [comment]
Ok, I just pulled your branch down, incremented version and pushed it back up.

**Comment by bdbcat** [comment]
Rick...
All fixed up in android_ci build.  The cloudsmith tarballs in "testplugin-alpha"  look good.
What is your plan to merge this branch?  Will you do it, or Jon?
Anyway, if you could PR the newly built android tarballs into the **master** catalog, I can do the final checks.
Please note that Android works mainly with the **master** catalog, and requires manual config editing to address the Beta and Alpha catalogs.  This was done to simplify the UI on Android, with its limited screen space.
Thanks
Dave

**Comment by rgleason** [comment]
Dear Dave,
Thank you!  It looks like flatpak is working too!  Thanks.  I will merge it into my master and make a PR to Jon's repository.
Then Push it to Plugins repository. Then I will be able to update other plugins to include android.

Tomorrow I will try to do vdr_pi.   (We rigged the sails again with friends and went for a wonderful sail today)

**Comment by bdbcat** [comment]
Rick...
Sounds like Jon will be offline for some time.
When you have merged android_ci to your master and rebuilt, you should be able to pull the tarballs from Cloudsmith and update the plugin master catalog, all before Jon merges your changes to his repo.  This would help me validate the Android system.
Thanks
Dave

**Comment by rgleason** [comment]
Have tried to Push testplugin, but it fails, probably due to need to add android to the Actions github check.
testplugin 1.0.133.0 add android fix flatpak #242

https://github.com/OpenCPN/plugins/issues/243

Let me know if you need another PR.

**Comment by bdbcat** [comment]
https://github.com/OpenCPN/plugins/issues/243#issuecomment-687946845

**Comment by rgleason** [comment]
Good that it's working now. Thank you Dave.
